### ISSUE TITLE
show birthdate & deathdate

### ISSUE THREAD

**Issue by kapcom01** [KapJep/RIP#23]
##

**Comment by jepeteo** [comment]
Where do you think this must be shown in the app?

**Comment by kapcom01** [comment]
I think a good choice is in the "actor's details widget" that I proposed in issue #27

**Comment by jepeteo** [comment]
ohh... ok! Thanks for making that clear.

**Comment by kapcom01** [comment]
haha :P 
the image that i have drawn is a little bit crap :P if you dont understand it, ask me.
